replace request.DATA by request.data
NotImplementedError: `request.DATA` has been deprecated in favor of
`request.data` since version 3.0, and has been fully removed
as of version 3.2.